apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spofblkpvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 300M
  storageClassName: linstor-xc
  volumeMode: Block
